#!/bin/bash

set -e

proj_name="$(basename "${PWD}")"
vertex_default_project="$(sed -n -e 's/project = \(.*\)/\1/' -e T -e p ~/.config/gcloud/configurations/config_default)"

mkdir -p ~/.claude
if ! [ -e ~/.claude.json ]; then
    printf '{}' >~/.claude.json
fi

if ! podman image exists claude:latest; then
    "$(dirname "${0}")/build-claude.sh"
fi

if ! podman secret exists claude-github-token; then
    echo '' | podman secret create claude-github-token -
fi

# Create directory for additional git config if it doesn't exist
mkdir -p ~/.config/git

exec podman run -i -t --tz=local \
    --name="claude-${proj_name}" --rm \
    --env "ANTHROPIC_VERTEX_PROJECT_ID=${vertex_default_project}" \
    --secret claude-github-token,type=env,target=GH_TOKEN \
    --userns=keep-id \
    --security-opt 'unmask=/proc/*' \
    --security-opt label=type:container_userns_t \
    --mount type=tmpfs,destination=/tmp/claude \
    --mount type=tmpfs,destination="/tmp/claude-$(id -ru)" \
    -v "${PWD}:/projects/${proj_name}:z" \
    -w "/projects/${proj_name}" \
    -v ~/.config/gcloud:/home/claude/.config/gcloud:z \
    -v ~/.gitconfig:/home/claude/.gitconfig:ro,z \
    -v ~/.config/git:/home/claude/.config/git:ro,z \
    -v ~/.claude:/home/claude/.claude:z \
    -v ~/.claude.json:/home/claude/.claude.json:z \
    localhost/claude:latest "$@"
